name: lint
on:
  push:
    branches:
    - master
  pull_request:
jobs:
  lint:
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.6'
    - name: Install Python dependencies
      run: pip install -r requirements.txt
    - name: flake8
      run: flake8 src test
    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: '0.11.14'
    - name: terraform
      run: terraform fmt --check
